#!/bin/sh
# From gist at https://gist.github.com/chadmaughan/5889802

# stash any unstaged changes
# git stash -q --keep-index

# run the tests with the gradle wrapper
./gradlew check --daemon

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
# git stash pop -q

# return the './gradlew check' exit code
exit $RESULT