global:
  tlsSecretName: ""
  ingressSubdomain: ""

base:
  runtime: spring

  image:
    repository: replace
    tag: replace
    port: 9080
    probePath: /
    # Overrides the image tag whose default is the chart appVersion.

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  # resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  route:
    enabled: true

  ingress:
    enabled: false

  env:
    - name: LOG_LEVEL
      value: "info"

  envFrom:
    - configMapRef:
        name: jaeger-config
        optional: true
    - secretRef:
        name: jaeger-access
        optional: true

  partOf: ""
  connectsTo: ""
